source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.4.9"

# Rails is a web-application framework that includes everything needed to create database-backed web applications according to the Model-View-Controller (MVC) pattern.
gem "rails", github: "rails/rails", branch: "8-1-stable"

# Pg is the Ruby interface to the PostgreSQL RDBMS. It works with PostgreSQL 9.3 and later.
gem "pg"

# Use the Puma web server [https://github.com/puma/puma/tags]
gem "puma", github: "puma/puma", tag: "v8.0.2"

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder"

# Hotwire"s modest JavaScript framework
# [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Integrate Tailwind CSS with the asset pipeline in Rails.
gem "tailwindcss-rails"

# With Rails 8, Propshaft is the default asset pipeline for new applications.
gem "propshaft"

# Pseudo `IO` class from/to `String`.
gem "stringio"

# Sass is a stylesheet language that’s compiled to CSS. It allows you to use variables, nested rules, mixins, functions, and more, all with a fully CSS-compatible syntax.
gem "dartsass-rails"

# Use JavaScript with ESM import maps
# [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Environment
gem "dotenv-rails"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "pry"

  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
    gem lib, git: "https://github.com/rspec/#{lib}.git", branch: "main"
  end

  # annotate
  gem "annotate"
end

group :test do
  # Database Cleaner is a set of gems containing strategies for cleaning your database in Ruby.
  gem "database_cleaner-active_record"

  # Faker is a ibrary for generating fake data such as names, addresses, and phone numbers.
  gem "faker"

  # factory_bot is a fixtures replacement
  gem "factory_bot_rails"

  # request spec helpers
  gem "rspec-json_expectations"
  gem "rails-controller-testing"

  # model spec helpers
  gem "shoulda-matchers"

  gem "rspec_junit_formatter"

  gem "simplecov", require: false
end

