require 'active_support'
require 'active_support/core_ext'
require 'dotenv/load'
require 'yaml'

# APP_HOSTNAME
if ENV['APP_HOSTNAME'].present?
  APP_HOSTNAME = ENV['APP_HOSTNAME']
else
  raise "Missing ENV APP_HOSTNAME"
end

# APP_PORT
if ENV['APP_PORT'].present?
  APP_PORT = ENV['APP_PORT']
else
  raise "Missing ENV APP_PORT"
end

# SECRET_KEY_BASE
if ENV['SECRET_KEY_BASE'].present?
  SECRET_KEY_BASE = ENV['SECRET_KEY_BASE']
else
  raise "Missing ENV SECRET_KEY_BASE"
end

# WEB_REGISTRATION_ENCRYPTION_KEY
# Shared by the frontend and the backend to encrypt the web registration payload
if ENV['WEB_REGISTRATION_ENCRYPTION_KEY'].present?
  if ENV['WEB_REGISTRATION_ENCRYPTION_KEY'].length < 32
    raise "ENV WEB_REGISTRATION_ENCRYPTION_KEY must be at least 32 characters"
  end
  WEB_REGISTRATION_ENCRYPTION_KEY = ENV['WEB_REGISTRATION_ENCRYPTION_KEY'][0, 32]
else
  raise "Missing ENV WEB_REGISTRATION_ENCRYPTION_KEY"
end

# NGINX_HOST
if ENV['NGINX_HOST'].present?
  NGINX_HOST = ENV['NGINX_HOST']
else
  raise "Missing ENV NGINX_HOST"
end

# NGINX_PORT
if ENV['NGINX_PORT'].present?
  NGINX_PORT = ENV['NGINX_PORT']
else
  raise "Missing ENV NGINX_PORT"
end

# NGINX_STATUS_PORT
if ENV['NGINX_STATUS_PORT'].present?
  NGINX_STATUS_PORT = ENV['NGINX_STATUS_PORT']
else
  raise "Missing ENV NGINX_STATUS_PORT"
end

# NGINX_WEB_REGISTRATION_PROTOCOL
# Optional, https by default: http to call a backend running locally
NGINX_WEB_REGISTRATION_PROTOCOL = ENV['NGINX_WEB_REGISTRATION_PROTOCOL'].presence || 'https'
unless %w[http https].include?(NGINX_WEB_REGISTRATION_PROTOCOL)
  raise "ENV NGINX_WEB_REGISTRATION_PROTOCOL must be http or https"
end

# NGINX_WEB_REGISTRATION_HOST
if ENV['NGINX_WEB_REGISTRATION_HOST'].present?
  NGINX_WEB_REGISTRATION_HOST = ENV['NGINX_WEB_REGISTRATION_HOST']
else
  raise "Missing ENV NGINX_WEB_REGISTRATION_HOST"
end

# NGINX_WEB_REGISTRATION_PORT
if ENV['NGINX_WEB_REGISTRATION_PORT'].present?
  NGINX_WEB_REGISTRATION_PORT = ENV['NGINX_WEB_REGISTRATION_PORT']
else
  raise "Missing ENV NGINX_WEB_REGISTRATION_PORT"
end

# NGINX_WEB_REGISTRATION_TOKEN
if ENV['NGINX_WEB_REGISTRATION_TOKEN'].present?
  NGINX_WEB_REGISTRATION_TOKEN = ENV['NGINX_WEB_REGISTRATION_TOKEN']
else
  raise "Missing ENV NGINX_WEB_REGISTRATION_TOKEN"
end

# POSTGRESQL_HOST
if ENV['POSTGRESQL_HOST'].present?
  POSTGRESQL_HOST = ENV['POSTGRESQL_HOST']
else
  raise "Missing ENV POSTGRESQL_HOST"
end

# POSTGRESQL_PORT
if ENV['POSTGRESQL_PORT'].present?
  POSTGRESQL_PORT = ENV['POSTGRESQL_PORT']
else
  raise "Missing ENV POSTGRESQL_PORT"
end

# POSTGRESQL_DB
if ENV['POSTGRESQL_DB'].present?
  POSTGRESQL_DB = ENV['POSTGRESQL_DB']
else
  raise "Missing ENV POSTGRESQL_DB"
end

# POSTGRESQL_USERNAME
if ENV['POSTGRESQL_USERNAME'].present?
  POSTGRESQL_USERNAME = ENV['POSTGRESQL_USERNAME']
else
  raise "Missing ENV POSTGRESQL_USERNAME"
end

# POSTGRESQL_PASSWORD
if ENV['POSTGRESQL_PASSWORD'].present?
  POSTGRESQL_PASSWORD = ENV['POSTGRESQL_PASSWORD']
else
  raise "Missing ENV POSTGRESQL_PASSWORD"
end

WEB_CONFIG                    = YAML.load_file(File.expand_path('../config/yaml/web_config.yaml', __dir__), symbolize_names: true).freeze
